[default.extend-words]

[files]
extend-exclude = [
    "CHANGELOG.md",
    "notebooks/*",
    "chat_server/fixtures/*",
    "chat_server/test.rest",
    "target/*",
    "migrations/*",
    "notify_server/*.html",
    ]
