
[workspace]
members = ["algo", "node-binding",]
resolver = "2"


[profile.release]
lto = true

[workspace.dependencies]
algo = { path = "algo" }
napi = { version = "2", default-features = false, features = ["full"] }
napi-derive = "2"
