/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function add(a: number, b: number): number
export type JsAlgo = Algo
export declare class Algo {
  constructor(name: string)
  getName(): string
  hash(data: string): string
}
